# Generated by Django 4.2.4 on 2025-02-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siterequest',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='siterequest',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='siterequest',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siterequest',
            name='website_type',
            field=models.CharField(choices=[('online-store', 'Online Store'), ('portfolio', 'Portfolio'), ('blog', 'Blog'), ('corporate', 'Corporate Website'), ('other', 'Other')], max_length=20),
        ),
    ]
