# Generated by Django 4.2.4 on 2025-02-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_rename_submitted_at_siterequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siterequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='siterequest',
            name='features',
        ),
        migrations.AddField(
            model_name='siterequest',
            name='website_features',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='siterequest',
            name='budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siterequest',
            name='website_type',
            field=models.CharField(choices=[('online-store', 'Online Store'), ('portfolio', 'Portfolio'), ('blog', 'Blog'), ('corporate', 'Corporate Website'), ('other', 'Other')], max_length=50),
        ),
    ]
